platform :ios, ‘9.0’

use_frameworks!

target 'TSReqKitDemo' do
    
    # pod 'TFKit',:git=>'/Users/threestonewang/Desktop/TFKit'
    # pod 'TSReqKit',:git=>'https://github.com/StoneStoneStoneWang/TSReqKit.git'
    
    pod 'AFNetworking', '~> 3.0'
    
    pod 'MJExtension'
    
    pod 'YYCache'
    
end
